name: Delete Old Artifacts Across All Branches

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Delete artifacts from non-latest build workflow runs across all branches
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARTIFACT_DELETE_TOKEN: ${{ secrets.ARTIFACT_DELETE_TOKEN }}
        run: |
          #!/bin/bash
          set -euo pipefail

          owner_repo="${GITHUB_REPOSITORY}"
          echo "Repository: $owner_repo"

          # Get a list of all branches
          echo "Fetching all branches..."
          branches_json=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${owner_repo}/branches?per_page=100")
          
          # Extract branch names
          all_branches=$(echo "$branches_json" | jq -r '.[].name')

          if [ -z "$all_branches" ]; then
            echo "No branches found to process."
            exit 0
          fi

          for branch_name in $all_branches; do
            echo "--- Processing branch: $branch_name ---"

            # List workflow runs for this specific branch
            runs_json=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/repos/${owner_repo}/actions/runs?branch=${branch_name}&per_page=100")

            latest_run_sha=""
            latest_run_id=""

            # Find the head_sha of the most recent completed CI Suite run on this branch
            # FIX: Explicitly convert .id to string before concatenation
            latest_ci_run=$(echo "$runs_json" | jq -r '.workflow_runs[] | select(.status=="completed" and .name=="CI Suite") | (.id | tostring) + " " + .head_sha' | head -n 1)
            
            if [ -n "$latest_ci_run" ]; then
              latest_run_id=$(echo "$latest_ci_run" | cut -d' ' -f1)
              latest_run_sha=$(echo "$latest_ci_run" | cut -d' ' -f2)
              echo "Latest CI Suite run on $branch_name: ID $latest_run_id, SHA $latest_run_sha"
            else
              echo "No completed 'CI Suite' workflow runs found on branch $branch_name. Skipping cleanup for this branch's runs."
              continue # Skip to the next branch if no completed CI Suite runs
            fi

            # Filter for workflow runs that are completed and that do not match the identified latest run's commit SHA
            delete_run_ids=$(echo "$runs_json" | jq --raw-output --arg latest_sha "$latest_run_sha" \
              '.workflow_runs[] | select(.head_sha != $latest_sha and .status=="completed" and .name=="CI Suite") | .id')

            if [ -z "$delete_run_ids" ]; then
              echo "No older, completed 'CI Suite' workflow runs found to clean up on branch $branch_name."
              continue
            fi

            for run_id in $delete_run_ids; do
              echo "Processing workflow run ID: $run_id on branch $branch_name"

              # List artifacts in this workflow run
              artifacts_json=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                "https://api.github.com/repos/${owner_repo}/actions/runs/${run_id}/artifacts")
              artifact_ids=$(echo "$artifacts_json" | jq --raw-output '.artifacts[] | .id')

              if [ -z "$artifact_ids" ]; then
                echo "No artifacts found for run $run_id on branch $branch_name"
                continue
              fi

              for artifact_id in $artifact_ids; do
                echo "Deleting artifact ID: $artifact_id from build run $run_id on branch $branch_name"
                curl -s -X DELETE -H "Authorization: token ${ARTIFACT_DELETE_TOKEN}" \
                  "https://api.github.com/repos/${owner_repo}/actions/artifacts/${artifact_id}"
              done
            done
            echo "--- Finished processing branch: $branch_name ---"
          done
