name: Publish on Tag

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NODE_ENV: production
      VITE_ANILIST_CLIENT_ID: ${{ secrets.ANILIST_CLIENT_ID }}
      VITE_ANILIST_CLIENT_SECRET: ${{ secrets.ANILIST_CLIENT_SECRET }}
      VITE_ANILIST_ENCRYPTION_KEY: ${{ secrets.ANILIST_ENCRYPTION_KEY }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        env:
          NPM_CONFIG_PRODUCTION: false
        run: npm ci --force
      - name: Build / Make (Windows)
        run: npm run make
      - name: Upload Windows Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-installers
          path: |
            out/make/squirrel.windows/x64/*.exe
            out/make/squirrel.windows/x64/*.msi
          if-no-files-found: warn

  build-macos:
    name: Build macOS
    runs-on: macos-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NODE_ENV: production
      VITE_ANILIST_CLIENT_ID: ${{ secrets.ANILIST_CLIENT_ID }}
      VITE_ANILIST_CLIENT_SECRET: ${{ secrets.ANILIST_CLIENT_SECRET }}
      VITE_ANILIST_ENCRYPTION_KEY: ${{ secrets.ANILIST_ENCRYPTION_KEY }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        env:
          NPM_CONFIG_PRODUCTION: false
        run: npm ci --force
      - name: Build / Make (macOS)
        run: npm run make
      - name: Upload macOS Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-installers
          path: |
            out/make/*.dmg
            out/make/zip/darwin/arm64/*.zip
          if-no-files-found: warn

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NODE_ENV: production
      VITE_ANILIST_CLIENT_ID: ${{ secrets.ANILIST_CLIENT_ID }}
      VITE_ANILIST_CLIENT_SECRET: ${{ secrets.ANILIST_CLIENT_SECRET }}
      VITE_ANILIST_ENCRYPTION_KEY: ${{ secrets.ANILIST_ENCRYPTION_KEY }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        env:
          NPM_CONFIG_PRODUCTION: false
        run: npm ci --force
      - name: Build / Make (Linux)
        run: npm run make
      - name: Upload Linux Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-installers
          path: |
            out/make/deb/x64/*.deb
          if-no-files-found: warn

  publish:
    name: Publish Release (aggregate)
    needs: [build-windows, build-macos, build-linux]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NODE_ENV: production
      VITE_ANILIST_CLIENT_ID: ${{ secrets.ANILIST_CLIENT_ID }}
      VITE_ANILIST_CLIENT_SECRET: ${{ secrets.ANILIST_CLIENT_SECRET }}
      VITE_ANILIST_ENCRYPTION_KEY: ${{ secrets.ANILIST_ENCRYPTION_KEY }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Windows installers
        uses: actions/download-artifact@v4
        with:
          name: windows-installers
          path: out/make/squirrel.windows/x64

      - name: Download macOS installers
        uses: actions/download-artifact@v4
        with:
          name: macos-installers
          path: out/make

      - name: Download Linux installers
        uses: actions/download-artifact@v4
        with:
          name: linux-installers
          path: out/make/deb/x64

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        env:
          NPM_CONFIG_PRODUCTION: false
        run: npm ci --force

      - name: Publish to GitHub Releases
        run: npm run publish -- --publish=always
