name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  publish:
    name: Publish Release (Stable)
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get version from package.json
        id: version
        run: |
          $version = (Get-Content package.json | ConvertFrom-Json).version
          echo "VERSION=$version" >> $env:GITHUB_OUTPUT
        shell: pwsh

      - name: Download installers from latest beta release
        run: |
          $beta_tag = "v${{ steps.version.outputs.VERSION }}-beta"

          # Create directory structure
          New-Item -ItemType Directory -Force -Path "out/make/squirrel.windows/x64" | Out-Null
          New-Item -ItemType Directory -Force -Path "out/make" | Out-Null
          New-Item -ItemType Directory -Force -Path "out/make/deb/x64" | Out-Null

          # Download all assets from the beta release
          gh release download "$beta_tag" -D out/make --pattern "*.exe"
          gh release download "$beta_tag" -D out/make --pattern "*.msi"
          gh release download "$beta_tag" -D out/make --pattern "*.dmg"
          gh release download "$beta_tag" -D out/make --pattern "*.zip"
          gh release download "$beta_tag" -D out/make --pattern "*.deb"

          # Move files to correct locations
          Get-ChildItem -Path "out/make/*.exe" -ErrorAction SilentlyContinue | Move-Item -Destination "out/make/squirrel.windows/x64/"
          Get-ChildItem -Path "out/make/*.msi" -ErrorAction SilentlyContinue | Move-Item -Destination "out/make/squirrel.windows/x64/"
          Get-ChildItem -Path "out/make/*.deb" -ErrorAction SilentlyContinue | Move-Item -Destination "out/make/deb/x64/"
        shell: pwsh

      - name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $tag = "${{ github.ref }}".Replace("refs/tags/", "")

          # Create stable release with installers from beta
          gh release create "$tag" `
            --title "v${{ steps.version.outputs.VERSION }}" `
            --notes "TBD" `
            out/make/squirrel.windows/x64/*.exe `
            out/make/squirrel.windows/x64/*.msi `
            out/make/*.dmg `
            out/make/*.zip `
            out/make/deb/x64/*.deb
        shell: pwsh
